import { StyleSheet } from 'react-native';
import { Color, Font, Radius, TextSize } from '@/constants/design';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Color.field,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 12,
    gap: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    backgroundColor: Color.chalk,
    borderRadius: Radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: Font.display.black,
    fontSize: 22,
    color: Color.fg1,
  },
  scrollContent: {
    padding: 16,
    gap: 20,
    paddingBottom: 48,
  },
  section: {
    gap: 8,
  },
  fieldLabel: {
    fontFamily: Font.mono.medium,
    fontSize: TextSize.xs,
    letterSpacing: 0.14 * TextSize.xs,
    color: Color.fg1,
    textTransform: 'uppercase',
  },
  hint: {
    fontFamily: Font.body.regular,
    fontSize: TextSize.sm,
    color: Color.fg3,
  },
  input: {
    fontFamily: Font.body.regular,
    fontSize: TextSize.base,
    color: Color.fg1,
    backgroundColor: Color.chalk,
    borderRadius: Radius.md,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: Color.border1,
  },
  rowInputs: {
    flexDirection: 'row',
    gap: 8,
  },
  chipsRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: Radius.pill,
    backgroundColor: Color.chalk,
    borderWidth: 1,
    borderColor: Color.border1,
  },
  chipActive: {
    backgroundColor: Color.pitch,
    borderColor: Color.pitch,
  },
  chipText: {
    fontFamily: Font.body.semibold,
    fontSize: TextSize.sm,
    color: Color.fg1,
  },
  chipTextActive: {
    color: Color.chalk,
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: Color.chalk,
    borderRadius: Radius.md,
    padding: 14,
  },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  stepperBtn: {
    width: 36,
    height: 36,
    borderRadius: Radius.sm,
    backgroundColor: Color.chalk,
    borderWidth: 1,
    borderColor: Color.border1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperValue: {
    fontFamily: Font.display.black,
    fontSize: TextSize.xl,
    color: Color.fg1,
    minWidth: 24,
    textAlign: 'center',
  },
  memberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 10,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: Color.border3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxActive: {
    backgroundColor: Color.grass500,
    borderColor: Color.grass500,
  },
  memberName: {
    fontFamily: Font.body.medium,
    fontSize: TextSize.base,
    color: Color.fg1,
  },
  createBtn: {
    backgroundColor: Color.pitch,
    borderRadius: Radius.lg,
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  createBtnText: {
    fontFamily: Font.body.bold,
    fontSize: TextSize.base,
    color: Color.chalk,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  opponentPicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: Color.chalk,
    borderRadius: Radius.md,
    padding: 14,
    borderWidth: 1,
    borderColor: Color.border1,
  },
  opponentAvatar: {
    width: 36,
    height: 36,
    borderRadius: Radius.sm,
    backgroundColor: Color.pitch,
    alignItems: 'center',
    justifyContent: 'center',
  },
  opponentAvatarText: {
    fontFamily: Font.display.black,
    fontSize: 12,
    color: Color.chalk,
  },
  opponentName: {
    fontFamily: Font.body.bold,
    fontSize: TextSize.base,
    color: Color.fg1,
  },
});
