import { Color, Font, Radius, TextSize } from '@/constants/design';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Color.field,
  },
  container: {
    padding: 20,
    gap: 16,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  pageTitle: {
    fontFamily: Font.display.black,
    fontSize: 28,
    color: Color.fg1,
    letterSpacing: -0.02 * 28,
  },
  bellBtn: {
    width: 44,
    height: 44,
    borderRadius: Radius.md,
    backgroundColor: Color.chalk,
    borderWidth: 1,
    borderColor: Color.border1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bellBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Color.clay,
    borderWidth: 2,
    borderColor: Color.field,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  bellBadgeText: {
    fontFamily: Font.mono.bold,
    fontSize: 10,
    color: Color.chalk,
  },
  avatarCard: {
    backgroundColor: Color.chalk,
    borderRadius: Radius.lg,
    padding: 24,
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: Color.border1,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: Radius.pill,
    backgroundColor: Color.pitch,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  avatarInitials: {
    fontFamily: Font.display.black,
    fontSize: 24,
    color: Color.chalk,
  },
  playerName: {
    fontFamily: Font.display.bold,
    fontSize: TextSize.md,
    color: Color.fg1,
  },
  card: {
    backgroundColor: Color.chalk,
    borderRadius: Radius.lg,
    padding: 20,
    gap: 12,
    borderWidth: 1,
    borderColor: Color.border1,
  },
  cardLabel: {
    fontFamily: Font.mono.medium,
    fontSize: TextSize.xs,
    letterSpacing: 0.14 * TextSize.xs,
    color: Color.fg3,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statName: {
    fontFamily: Font.body.regular,
    fontSize: TextSize.sm,
    color: Color.fg2,
  },
  statValue: {
    fontFamily: Font.display.bold,
    fontSize: 18,
    color: Color.fg1,
  },
  statValueSmall: {
    fontFamily: Font.body.semibold,
    fontSize: TextSize.sm,
    color: Color.fg1,
  },
  editLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  editLinkText: {
    fontFamily: Font.body.semibold,
    fontSize: TextSize.sm,
    color: Color.grass600,
  },
  btnSecondary: {
    backgroundColor: Color.chalk,
    paddingVertical: 16,
    borderRadius: Radius.sm,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: Color.border3,
  },
  btnSecondaryText: {
    fontFamily: Font.body.bold,
    fontSize: TextSize.sm,
    color: Color.fg1,
    letterSpacing: 0.5,
  },
  btnLogout: {
    backgroundColor: Color.chalk,
    paddingVertical: 16,
    borderRadius: Radius.sm,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#DC2626',
  },
  btnLogoutText: {
    fontFamily: Font.body.bold,
    fontSize: TextSize.sm,
    color: '#DC2626',
    letterSpacing: 0.5,
  },
});
